CREATE TABLE IF NOT EXISTS "Teller" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"LastName"	TEXT NOT NULL,
	"User"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Transactions" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Number"	TEXT NOT NULL UNIQUE,
	"DateTime"	TEXT NOT NULL,
	"Amount"	NUMERIC NOT NULL,
	"Type"	TEXT NOT NULL,
	"Details"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "University" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"DepositAmount"	NUMERIC NOT NULL,
	"User"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL UNIQUE,
	"Phone"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "User" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"LastName"	TEXT NOT NULL,
	"User"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL,
	"Phone"	TEXT,
	"Address"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "BussinessAccount" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Number"	TEXT NOT NULL UNIQUE,
	"Balance"	NUMERIC NOT NULL,
	"Currency"	TEXT NOT NULL,
	"Type"	TEXT NOT NULL,
	"Status"	TEXT NOT NULL,
	"BussinessID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("BussinessID") REFERENCES "University"("ID")
);
CREATE TABLE IF NOT EXISTS "PersonalAccount" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Number"	TEXT NOT NULL UNIQUE,
	"Balance"	NUMERIC NOT NULL,
	"Currency"	TEXT NOT NULL,
	"Type"	TEXT NOT NULL,
	"Status"	TEXT NOT NULL,
	"UserID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("UserID") REFERENCES "User"("ID")
);
CREATE TABLE IF NOT EXISTS "UniversityServiceLocal" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"ClientID"	TEXT NOT NULL,
	"ClientName"	TEXT NOT NULL,
	"StudentCode"	TEXT NOT NULL,
	"Details"	TEXT,
	"UniversitAccountID"	INTEGER NOT NULL,
	"TellerID"	INTEGER NOT NULL,
	"TransactionID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("TellerID") REFERENCES "Teller"("ID"),
	FOREIGN KEY("UniversitAccountID") REFERENCES "BussinessAccount"("ID"),
	FOREIGN KEY("TransactionID") REFERENCES "Transaction"("ID")
);
CREATE TABLE IF NOT EXISTS "UniversityServiceOnline" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"StudentCode"	TEXT NOT NULL,
	"Details"	TEXT,
	"UniversityAccountID"	INTEGER NOT NULL,
	"UserAccountID"	INTEGER NOT NULL,
	"TransactionID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("UserAccountID") REFERENCES "PersonalAccount"("ID"),
	FOREIGN KEY("UniversityAccountID") REFERENCES "BussinessAccount"("ID"),
	FOREIGN KEY("TransactionID") REFERENCES "Transaction"("ID")
);